### ISSUE TITLE
Image Downloader

### ISSUE THREAD

**Issue by dburnsii** [lauriharpf/thecocktaildb-downloader#1]
**Is your feature request related to a problem? Please describe.**
I'd like to use thecocktaildb for an offline project, complete with images for each cocktail

**Describe the solution you'd like**
For the database to be completely offline, there must be a way to download images from the cocktail db

**Describe alternatives you've considered**
Images could be stored as blobs in the database itself (would end up being pretty large), or stored in a separate folder for access.

**Comment by lauriharpf** [comment]
Sorry for the delay in response and thank you for the suggestion, it sounds like a good idea.

Other commitments have kept me from working on this project, but I'll try to allocate time to implement this in the future. Of course, PR's are also welcome if someone gets to it first!

**Comment by lauriharpf** [comment]
@dburnsii, does the [with-images](https://github.com/lauriharpf/thecocktaildb-downloader/tree/master/thecocktaildb/src/generated/with-images) -version of the data meet your use case?

The downloader now also fetches the images, so I'm closing this issue. But please comment or open a new issue if the current solution isn't matching your needs.
